// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $api_containers_index from "./routes/api/containers/index.ts";
import * as $api_containers_id_logs from "./routes/api/containers/[id]/logs.ts";
import * as $api_containers_id_kill from "./routes/api/containers/[id]/kill.ts";
import * as $Dashboard from "./islands/Dashboard.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/api/containers/index.ts": $api_containers_index,
    "./routes/api/containers/[id]/logs.ts": $api_containers_id_logs,
    "./routes/api/containers/[id]/kill.ts": $api_containers_id_kill,
  },
  islands: {
    "./islands/Dashboard.tsx": $Dashboard,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
